<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [1]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

lists

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

Numpy arrays

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

Dictionaries

In [6]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

Dictionaries:

1. They use a key and an associated value separated by a ```:```
2. The value can be accessed by making use of the key that is associated with it

## 1.2 Accessing data from a list (or array)

The first element in any python list or array has the index 0. Therefore the first element is 0, the second is 1 and so on.


In [7]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [11]:
py_real_names[0] #first element of py_real_names

'Natasha Romanoff'

In [9]:
py_super_names[0]  #first element of py_super_names

'Black Widow'

In [12]:
py_super_names[2] # 3rd element of py_super_names

'Doctor Strange'

In [13]:
py_super_names[-1]   # last element of py_super_names

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [15]:
superhero_info = {                                # The dictionary
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [18]:
superhero_info["Natasha Romanoff"]  #pass the key into the dictionary to access the value associated with it

'Black Widow'

In [20]:
superhero_info.keys()  #to access all the keys of the dictionary

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [21]:
superhero_info.values() #to access all the values of the dictionary

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [4]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],    #2D list!
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]


# 2 Lists vs. Arrays

## 2.1 Size

In [26]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [30]:
len(py_list_2d) 

10

In [33]:
len(np_array_2d)

10

In [34]:
np_array_2d.shape # the .shape part does not have brackets as .shape is an attribute of np_array_2d

(10, 2)

## 2.2 Arrays are fussy about type

lists can accomodate different datatypes as elements in itself however arrays require that all its elements be of the same datatype

In [35]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [36]:
py_list
np_array

array(['1', '1.5', 'A'], dtype='<U32')

There is a workaround for datasets with different datatypes. For example one could use ```astypes()``` to cast all the data to be a single datatype

## 2.3 Adding a number

In [37]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [38]:
np_array + 10 #adds to every element of the array

array([11, 12, 13, 14, 15])

In [40]:
py_list + 10        # returns an error as this does not work

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [41]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [43]:
py_list_1 + py_list_2   #both lists will be concatenated together

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [45]:
np_array_1 + np_array_2 #each element will be added to the element from the other array for numbers at the same index

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [46]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [48]:
py_list*2  # the same list is concatenated to itself 

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [50]:
np_array*2 # the number is multiplied to each element of the array

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [51]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [52]:
np_array**2                     #each element of the array is squared

array([ 1,  4,  9, 16, 25])

In [53]:
py_list**2                      # doesnt work

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [54]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [55]:
py_list == 3     #it is comparing the datatypes of 3 and the list. Since they are both different so it returns False

False

In [60]:
py_list > 3      # Just doesnt make sense

TypeError: '>' not supported between instances of 'list' and 'int'

In [58]:
np_array == 3  #it is checkig if every element is equal to 3

array([False, False,  True, False, False])

In [59]:
np_array > 3  #it is checking if every element is greater than 3

array([False, False, False,  True,  True])

## 2.8 Mathematics

Examples of mathematics that can be applied to lsits/arrays

In [61]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [62]:
sum(py_list)     # sum() is a base Python function


15

In [63]:
max(py_list)     # max() is a base Python function


5

In [64]:
min(py_list)     # min() is a base Python function


1

In [65]:
np_array.sum()


15

In [66]:
np_array.max()


5

In [67]:
np_array.min()


1

In [68]:
np_array.mean()


3.0

In [69]:
np_array.std()

1.4142135623730951

In [70]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

As a rough guide, operations on a list work on a whole list while operations on arrays work on individual elements