<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# Subsetting: Indexing and Slicing

1. Subsetting means to select something (a subset)
2. Indexing refers to selecting one element of an array or list
3. Slicing refers to selecting a range of elements

## Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
import numpy as np

In [4]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  #chose py list

| Syntax     | Result             | Note                              |
|------------|--------------------|-----------------------------------|
| `x[0]`     | 'a1'               | First element                     |
| `x[-1]`    | 'j10'              | Last element                      |
| `x[0:3]`   | ['a1', 'b2', 'c3'] | Gives 3 − 0 = 3 elements          |
| `x[1:6]`   | ['b2', 'c3', 'd4', 'e5', 'f6'] | Gives 6 − 1 = 5 elements |
| `x[1:6:2]` | ['b2', 'd4', 'f6'] | Gives every other of 6 − 1 = 5 elements |
| `x[5:]`    | ['f6', 'g7', 'h8', 'i9', 'j10'] | Gives len(x) −5 = 5 elements |
| `x[:5]`    | ['a1', 'b2', 'c3', 'd4', 'e5'] | Gives 5 − 0 = 5 elements |
| `x[5:2:-1]`| ['f6', 'e5', 'd4'] | Gives 5 − 2 = 3 elements (i.e., in reverse) |
| `x[::-1]`  | Reverses the list  |                                   |


general format for slicing:
```x[start:stop:step]```

## 1.2 Arrays only | Subsetting by masking

MASKING: Only works with numpy arrays

In [12]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3  #the mask condition
my_mask  # list of results

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [11]:
np_array[my_mask] #The mask showing the values that fulfill the condition

array([ 4,  5,  6,  7,  8,  9, 10])

Subsetting by masking only works with numpy arrays

In [13]:
np_array[np_array > 3]  #directly applying the mask to the array

array([ 4,  5,  6,  7,  8,  9, 10])

In [16]:
np_array[~(np_array > 3)]     # '~' means 'NOT' aka 'Bitwise operator', therefore output are values that dont fulfill the condition

array([1, 2, 3])

In [18]:
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND', returns values that fulfill the conditions on either side of '&'

array([4, 5, 6, 7])

In [20]:
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR', returns values that fulfill at least one condition

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [ ]:
The differences between lists and arrays become more 

In [22]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [29]:
py_list_2d[3]  #access the 3rd sublist

[4, 'D']

In [25]:
np_array_2d[3]  

array(['4', 'D'], dtype='<U11')

In [28]:
py_list_2d[3][0]   #access 3rd sublist then access the first element of the sublist


4

In [27]:
np_array_2d[3, 0] #arrays uses a single pair of square brackets

'4'

In [30]:
py_list_2d[:3]


[[1, 'A'], [2, 'B'], [3, 'C']]

In [31]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [32]:
py_list_2d[:3][0] #access the first 3 elements then acccess the first element of theat slice

[1, 'A']

In [34]:
np_array_2d[:3, 0] #access the first element of the first 3 sublists

array(['1', '2', '3'], dtype='<U11')

In [35]:
py_list_2d[3:6][0] #access first sublist of the slice of the 4th to 5th elements

[4, 'D']

In [36]:
np_array_2d[3:6, 0]  #access the first element of the slce of the 4th to 5th elements

array(['4', '5', '6'], dtype='<U11')

In [38]:
np_array_2d[:, 0]  #from all sublists in the array, chose the first element 

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

## 1.4 Growing lists

In [39]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [40]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [41]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [43]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x     #Using append is about 1.5 times faster than the other operations above

[1, 2, 3, 4]

In [44]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [45]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [46]:
x=[1, 2, 3]
x.append([4, 5, 6])
x  #appending adds the list to the original list as a sublist (with brackets) while the other operations remove the brackets.

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

A tuple is like a list and uses ```()``` brackets. However they are immutable. You can access the data but cannot change the original tuple

In [48]:
a=(1, 2, 3)     # Defining a tuple

In [49]:
print(a[0])    # Access data

1


In [50]:
# The following will NOT work
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In order to create a copy of the tuple

In [58]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [59]:
y.append(4)
y

[1, 2, 3, 4]

In [3]:
x=[1, 2, 3]
y=x.copy()    #a shallow copy of x is created
z=x           #z points to the original list x

x.append(4)

In [4]:
print(y)     #therefore the copy of x when manipulated, will not reflect in y

[1, 2, 3]


In [7]:
print(z)    #therefore the any changes to x will also be reflected in z

[1, 2, 3, 4]


# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes